config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :payments
  resources :categories
  get '/user', to: 'categories#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { minimum: 3, maximum: 250 }
  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Payment.find(params[:id])
  end

  # POST /payments or /payments.json
  def create
    if current_user.nil?
      redirect_to payments_path
      return
    end
    name = payment_params[:name]
    amount = payment_params[:amount]
    @payment = Payment.new(name:, amount:)
    @payment.user_id = current_user.id
    payment_params[:categories].each do |category|
      @payment.categories.push(Category.find(category)) unless category == ''
    end

    respond_to do |format|
      if @payment.save
        format.html { redirect_to category_url(@payment.categories[0]), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Payment.find(params[:id])

    name = payment_params[:name]
    amount = payment_params[:amount]
    categories = payment_params[:categories]
    categories.delete_at(0)
    categories = categories.map { |category_id| Category.find(category_id) }
    respond_to do |format|
      if @payment.update(name:, amount:, categories:)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Payment.find(params[:id])

    @payment.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, categories: [])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div>
      <a href="<%= if @payment.categories[0] then category_path(@payment.categories[0]) else payments_path end %>">
        <img class="arrow-left" src="https://budget-app-003.herokuapp.com/assets/back-c280a48ad5854403fd742c6c71f80ff505caec9ff3e28f61dc6a02a1dfbfd30c.svg">
      </a>
    </div>
    <h4 class="register-title"><%= title %></h4>
    <div> </div>
  </div>
  <%= form_with(model: payment) do |form| %>
    <% if payment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

        <ul>
          <% payment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.text_field :name, placeholder: "Name", class: "reg-input" %>
    </div>

    <div>
      <%= form.number_field :amount, placeholder: "Amount", class: "reg-input" %>
    </div>

    <div>
      <%= form.select :categories, Category.where(user_id: current_user.id).collect {|cat| [cat.name, cat.id]}, { include_blank: false }, required: true, class:"", multiple: true %>
    </div>

    <div class="add-category-btn-container">
      <%= form.submit button_title, class: "create-category-btn" %>
    </div>
  <% end %>
</div>

app/views/payments/_payment.html.erb
<a href="<%= "#{payments_path}/#{payment.id}" %>" class="category-link" >
  <div id="<%= dom_id payment %>" class="payment-container payment-height">
    <div>
      <strong>Categories:</strong>
      <%= payment.categories.map { |category| category.name }.join(', ') %>
      &nbsp;
    </div>

    <p>
      <strong>Name:</strong>
      <%= payment.name %>
      &nbsp;
    </p>

    <p>
      <strong>Amount:</strong>
      $<%= payment.amount %>
    </p>
  </div>
</a>

app/views/payments/edit.html.erb
<%= render "form", payment: @payment, title: "EDITING PAYMENT", button_title: "SUBMIT" %>

app/views/payments/index.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div> </div>
    <h4 class="register-title">PAYMENTS</h4>
    <div class="actions">
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'sign-up-form-btn' %>
    </div>
  </div>

  <div id="payments">
    <% @payments.each do |payment| %>
      <%= render payment %>
    <% end %>
  </div>
  <div class="add-category-btn-container">
    <%= link_to "New payment", new_payment_path, class: "add-category-btn" %>
  </div>
</div>

app/views/payments/new.html.erb
<%= render "form", payment: @payment, title: "NEW PAYMENT", button_title: "CREATE PAYMENT" %>

app/views/payments/show.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div>
      <a href="<%= category_path(@payment.categories[0]) %>">
        <img class="arrow-left" src="https://budget-app-003.herokuapp.com/assets/back-c280a48ad5854403fd742c6c71f80ff505caec9ff3e28f61dc6a02a1dfbfd30c.svg">
      </a>
    </div>
    <h4 class="register-title">PAYMENT DETAILS</h4>
    <div> </div>
  </div>
  <%= render @payment %>

  <% if can? :update, @payment %>
    <div class="category-details-btn-container">
      <%= link_to "EDIT", edit_payment_path(@payment), class: "edit-category-btn" %>

      <%= button_to "DESTROY", @payment, method: :delete, class: "destroy-category-btn" %>
    </div>
  <% end %>
</div>