config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :payments
  resources :categories
  get '/user', to: 'categories#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :payments

  validates :name, presence: true, length: { minimum: 3, maximum: 250 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @payments = Category.find(params[:id]).payments
    render 'payments/index'
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category_icons = [
      ['Education', ActionController::Base.helpers.image_path('education.png')],
      ['Entertainment', ActionController::Base.helpers.image_path('entertainment.png')],
      ['Healthcare', ActionController::Base.helpers.image_path('healthcare.png')],
      ['Shopping', ActionController::Base.helpers.image_path('shopping.png')],
      ['Utilities', ActionController::Base.helpers.image_path('utilities.png')],
      ['Other', ActionController::Base.helpers.image_path('other.png')]
    ]
  end

  # GET /categories/1/edit
  def edit
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Category.find(params[:id])

    @category_icons = [
      ['Education', ActionController::Base.helpers.image_path('education.png')],
      ['Entertainment', ActionController::Base.helpers.image_path('entertainment.png')],
      ['Healthcare', ActionController::Base.helpers.image_path('healthcare.png')],
      ['Shopping', ActionController::Base.helpers.image_path('shopping.png')],
      ['Utilities', ActionController::Base.helpers.image_path('utilities.png')],
      ['Other', ActionController::Base.helpers.image_path('other.png')]
    ]
  end

  # POST /categories or /categories.json
  def create
    if current_user.nil?
      redirect_to categories_path
      return
    end
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Category.find(params[:id])

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    raise ActiveRecord::RecordNotFound, 'Record not found.' if cannot? :update, Category.find(params[:id])

    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<a href="<%= "#{categories_path}/#{category.id}" %>" class="category-link" >
  <div id="<%= dom_id category %>" class="category-container" >
    <div class="icon-container">
      <%= image_tag category.icon, alt: "rss feed", class: "category-icon" %>
      <%= category.name %>
    </div>

    <div><%= category.user.name %></div>

    <div>
      Total: $<%= category.payments.inject(0){ |sum, payment| sum + payment.amount } %>
    </div>
  </div>
</a>

app/views/categories/_form.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div>
      <a href="<%= categories_path %>">
        <img class="arrow-left" src="https://budget-app-003.herokuapp.com/assets/back-c280a48ad5854403fd742c6c71f80ff505caec9ff3e28f61dc6a02a1dfbfd30c.svg">
      </a>
    </div>
    <h4 class="register-title"><%= title %></h4>
    <div> </div>
  </div>
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.text_field :name, placeholder: "Name", class: "reg-input" %>
    </div>

    <div>
      <%= form.select :icon, @category_icons, :prompt => 'Select an icon', class: 'reg-input', required: true %>
    </div>

    <div class="add-category-btn-container">
      <%= form.submit button_title, class: "create-category-btn" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render "form", category: @category, title: 'EDIT CATEGORY', button_title: 'SUBMIT' %>

app/views/categories/index.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div> </div>
    <h4 class="register-title">CATEGORIES</h4>
    <div class="actions">
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'sign-up-form-btn' %>
    </div>
  </div>

  <div id="categories">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
  <div class="add-category-btn-container">
    <%= link_to "NEW CATEGORY", new_category_path, class: "add-category-btn" %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category, title: 'NEW CATEGORY', button_title: 'CREATE CATEGORY' %>

app/views/categories/show.html.erb
<div class="register-container">
  <div class="navigation-header">
    <div>
      <a href="<%= categories_path %>">
        <img class="arrow-left" src="https://budget-app-003.herokuapp.com/assets/back-c280a48ad5854403fd742c6c71f80ff505caec9ff3e28f61dc6a02a1dfbfd30c.svg">
      </a>
    </div>
    <h4 class="register-title">CATEGORY DETAILS</h4>
    <div> </div>
  </div>
  <%= render @category %>

  <% if can? update:, @category %>
    <div class="category-details-btn-container">
      <%= link_to "EDIT", edit_category_path(@category), class: "edit-category-btn" %>

      <%= button_to "DESTROY", @category, method: :delete, class: "destroy-category-btn" %>
    </div>
  <% end %>
</div>